### ISSUE TITLE
Your ClientId and other information are exposed, pay attention to safety

### ISSUE THREAD

**Issue by ertu426** [uguisuan/UE4_OSSEOS_Sample#1]
Google Translate:
I want to learn your technology. After downloading, I found that your ClientId and other information were exposed. I think you should modify it. Be safe.

中文:
我想学习您的技术,下载之后发现您的ClientId等信息暴露了, 我觉得您是否应该修改一下呢.注意安全.

**Comment by uguisuan** [comment]
Removed file Config/DefaultEngine.ini from repo using git filter-branch and added again without credentials.
Thank you for your comments.
